# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Moxin Tang"
description: "Industrial Engineering · Optimization · Machine Learning"
url: "https://hingma.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

locale: "en-US"
timezone: Asia/Shanghai

plugins:
  - jekyll-include-cache

author:
  name: "Moxin Tang"
  avatar: "/assets/images/avatar.jpg"   # 你之后放头像
  bio: >
    Industrial Engineering · Optimization · Machine Learning  
    工业工程｜优化｜机器学习
  location: "China"
  email: ""   # 可选
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hingma"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: ""
    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/cv/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
